### ISSUE TITLE
less travel for kids

### ISSUE THREAD

**Issue by maciekboni** [bonilab/Temple-Malaria-Simulation#7]
introduce a new YAML input file option that looks like:

   relative_probability_that_child_travels_compared_to_adult : 0.25

which could of course be set to

   relative_probability_that_child_travels_compared_to_adult : 1.0

meaning that children and adults travel at the same rates.

If the relative probability is something like 0.25 then every time a child (under 18) gets selected to travel then you do another coin flip ( random draw on [0,1] ) to see if the number is lower than 0.25.  If it is, the child will be allowed to travel.

**Comment by merlinvn** [comment]
To configure the relative_probability_that_child_travels_compared_to_adult in your input file, please append the field entry under the circulation_info section:

```yaml
circulation_info:
  max_relative_moving_value: 35
  number_of_moving_levels: 100
  moving_level_distribution:
    distribution: Gamma
    Exponential:
      scale: 0.17
    Gamma:
      mean: 5
      sd: 10
  circulation_percent: 0.00336
## new field here
  relative_probability_that_child_travels_compared_to_adult: 1.0
## end of new field  
  length_of_stay:
    mean: 5
    sd: 10
```

In case the `relative_probability_that_child_travels_compared_to_adult` field is missing from your configuration, the simulation defaults to a value of `1.0`. This default behavior can be verified in the output log.

Currently, the simulation has the age threshold of 18 years hard-coded into its logic. 

This feature has been implemented in: 
https://github.com/bonilab/Temple-Malaria-Simulation/commit/4f928bab067a3fa459eb7ebd7c862d85a8b4cd89
